Feature/dbi-61 - Atualizar o READ ME com o fluxo do git flow
dbinclui-org/dbinclui-frontend pull request #14
Opened 2021-12-20 19:16 UTC by brunomdrrosa

2021-12-20 19:34 UTC, eduardoaraya requested changes

2021-12-20 19:34 UTC, eduardoaraya commented on README.md
> +$ git clone https://github.com/dbinclui/dbinclui-backend.git
Essa parte você pode manter como frontend mesmo

2021-12-20 19:34 UTC, eduardoaraya commented on README.md
> +### Iniciando o Backend com Nodemon
Não precisamos dessa instrução aqui no front

2021-12-20 19:34 UTC, eduardoaraya commented on README.md
> +$ npm run dev
Acho que o script correto é npm start

2021-12-20 19:34 UTC, eduardoaraya commented on README.md
> +$ git clone https://github.com/dbinclui/dbinclui-backend.git
Alterar para frontend e apontar para o repo da org

2021-12-20 19:48 UTC, brunomdrrosa reviewed
Realizada as alterações dos textos sobre o backend que estavam no README

2021-12-20 21:00 UTC, arthurvergacas approved these changes
### topissimo
adorei as imagens inclusive noh :sparkles:

2021-12-21 13:12 UTC, eduardoaraya approved these changes

2021-12-21 13:13 UTC, merged