Feature/dbi 51
dbinclui-org/dbinclui-frontend pull request #20
Opened 2021-12-23 13:15 UTC by ketrynsdm

Page home

2021-12-23 16:07 UTC, fabiojcbatista approved these changes

2021-12-23 20:01 UTC, lorenaaze approved these changes

2021-12-27 13:47 UTC, fabiojcbatista approved these changes

2021-12-27 14:25 UTC, eduardoaraya requested changes

2021-12-27 14:25 UTC, eduardoaraya commented on src/index.tsx
> -ReactDOM.render(<App />, document.getElementById('root'));
Essa alteração dever ser mantida

2021-12-27 14:25 UTC, eduardoaraya commented on src/App.tsx
>  function App() {
Essa alteração dever ser mantida.

2021-12-27 14:25 UTC, eduardoaraya commented on src/pages/home/style.css
> +p{
Não utilizar a tag pura, pois dessa forma irá pegar globalmente. Isso aferatá todas as tags `p` da aplicação.

2021-12-27 18:37 UTC, eduardoaraya commented on package.json
> +    "ts-jest": "^27.1.2",
Remover essa lib ela ja vem como dependencia do react `ts-jest": "^27.1.2"`

2021-12-27 21:51 UTC, closed without merging