Feature/dbi us001-10 - Fazer footer
dbinclui-org/dbinclui-frontend pull request #27
Opened 2021-12-28 20:22 UTC by brunomdrrosa

## Descrição

Foi realizado o Footer para a aplicação

____

**Link do card:** [US001 - [Front] - Fazer footer](https://trello.com/c/h3S6vA5a/10-us001-front-fazer-footer)

____

## Checklist Code Review
Avaliar se todos os itens a seguir foram feitos. Os itens com `*` não são obrigatórios.

- [X] Foi adicionada a descrição da PR
- [X] Foi adicionado o link do card
- [X] A branch segue o padrão com o prefixo DBI
- [X] Está seguindo os padrões de prefixo do gitflow (feature, bugfix, hotfix, release)
- [X] O título da PR segue o padrão: ***Nome da branch - Título do card***
- [X] A PR está sendo enviada para a branch `develop`
- [X] O Repositório que a PR está sendo enviada é o [**dbinclui-org/dbinclui-frontend**](https://github.com/dbinclui-org/dbinclui-frontend)
- [X] Foi realizado os testes unitários *
- [ ] Foi realizado os testes de E2E *
- [X] Foi adicionada as respectivas **labels**
- [X] A PR foi assinada

Para que haja uma padronização na criação dos componentes, este deve seguir o seguinte modelo de construção:

- [X] Deve ser feita a importação do _React_ no escopo do componente.
- [X] Deve conter uma _interface_ com as propriedades do componente.
- [X] Nome da _interface_ deve ter o sufixo _Props_.
- [X] Recebe _React.FC_, no qual recebe a _interface_
- [X] Deve retornar elemento _JSX_
- [X] O componente de ser exportado ao final como `default`.
 
Exemplo:
```tsx
import React from 'react';

export interface ComponetNameProps {}

export const ComponetName: React.FC<ComponentNameProps> = (): JSX.Element => {
  return <>...</>;
};

export default ComponentName;
```

2021-12-28 20:56 UTC, lorenaaze submitted a review, later dismissed

2021-12-29 12:50 UTC, Luh-Santos requested changes
Nos target={'_blank'} além do noreferrer tem que ter o noopener.
rel=”noopener noreferrer”

2021-12-29 13:31 UTC, Luh-Santos approved these changes

2021-12-29 13:45 UTC, Luh-Santos requested changes
Ficou uma borda branca abaixo do footer tanto no mobile quanto no desktop

2021-12-29 14:14 UTC, Luh-Santos approved these changes

2021-12-29 18:29 UTC, nickolasL13 approved these changes

2021-12-29 18:49 UTC, arthurvergacas approved these changes

2021-12-29 20:11 UTC, merged