Feature/dbi 49 - Configurar biblioteca e estrutura de roteamento/navegação
dbinclui-org/dbinclui-frontend pull request #3
Opened 2021-12-16 20:42 UTC by lorenaaze

2021-12-16 21:35 UTC, arthurvergacas approved these changes
## Acho que ta TOPISSIMO

Única coisa que eu penso é que talvez fosse melhor abstrair o `<BrowserRouter></BrowserRouter>` pra um componente próprio, pq aí tem menos risco de ficar uma identação toda esquisita.

Por exemplo, um cenário hipotetico aqui do futuro. Se a gente continuar colocando as rotas `index.tsx` pode virar algo tipo:

```tsx
ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <AuthContextProvider>
        <Routes>
          <Route path="/" element={<App/>}/>
            <Route index element={<Home/>}/>
              <CurrentGuideContextProvider>
                <Route path="guia-acessibilidade" element={<AcessibilityGuide/>}>
                  <Route path=":idAcessibilidade" element={<AcessibilityGuideDetails/>}/>
                </Route>
              </CurrentGuideContextProvider>
              <Route path="guia-cultura-surda" element={<DeafCultureGuide/>}/>
            <Route path="*" element={<Error/>}/>
        </Routes>
      </AuthContextProvider>
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
); 
```

Eu inventei umas coisa aí ne, mas acho que não é dificil de ficar assim mais pra frente. Aí por isso talvez seja melhor ter só um wrapper pras rotas, mas não tenho certeza.

De qualquer forma ta LINDISSIMO ARRASARAM!!!! :tada: :1st_place_medal: :100: mds esses emojis do github sao incriveis vcs sao :top: KKKKKKKKKK

2021-12-16 22:31 UTC, AndersonMoura333 approved these changes

2021-12-17 12:38 UTC, eduardoaraya requested changes
Alterar o nome do arquivo `src/pages/error/index.tsx` para o código do erro quando o conteúdo não for encontrado, no caso é o 404. `src/pages/error/404.tsx`

https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status

2021-12-17 12:38 UTC, eduardoaraya commented on package.json
> +    "jest": "^26.6.0",
Mover o jest para `devDependencies`

2021-12-17 14:38 UTC, arthurvergacas approved these changes

2021-12-17 14:43 UTC, eduardoaraya approved these changes

2021-12-17 16:01 UTC, merged