US003 - [Front] - Validar dados
dbinclui-org/dbinclui-frontend pull request #30
Opened 2021-12-29 21:00 UTC by roazambuja

## Descrição

Foi desenvolvida a validação de dados do formulário de cadastro de novo guia. Adicionamos os elementos necessários para validação de dados e realizamos os testes.

____

**Link do card:**
[US003 - [Front] - Validar dados](https://trello.com/c/vE5HlCDv/22-us003-front-validar-dados)

____

## Checklist Code Review
Avaliar se todos os itens a seguir foram feitos. Os itens com `*` não são obrigatórios.

- [ ] Foi adicionada a descrição da PR
- [ ] Foi adicionado o link do card
- [ ] A branch segue o padrão com o prefixo DBI
- [ ] Está seguindo os padrões de prefixo do gitflow (feature, bugfix, hotfix, release)
- [ ] O título da PR segue o padrão: ***Nome da branch - Título do card***
- [ ] A PR está sendo enviada para a branch `develop`
- [ ] O Repositório que a PR está sendo enviada é o [**dbinclui-org/dbinclui-frontend**](https://github.com/dbinclui-org/dbinclui-frontend)
- [ ] Foi realizado os testes unitários *
- [ ] Foi realizado os testes de E2E *
- [ ] Foi adicionada as respectivas **labels**
- [ ] A PR foi assinada

Para que haja uma padronização na criação dos componentes, este deve seguir o seguinte modelo de construção:

- [ ] Deve ser feita a importação do _React_ no escopo do componente.
- [ ] Deve conter uma _interface_ com as propriedades do componente.
- [ ] Nome da _interface_ deve ter o sufixo _Props_.
- [ ] Recebe _React.FC_, no qual recebe a _interface_
- [ ] Deve retornar elemento _JSX_
- [ ] O componente de ser exportado ao final como `default`.
 
Exemplo:
```tsx
import React from 'react';

export interface ComponetNameProps {}

export const ComponetName: React.FC<ComponentNameProps> = (): JSX.Element => {
  return <>...</>;
};

export default ComponentName;
```

2021-12-29 22:03 UTC, fabiojcbatista reviewed
Nome da branch--------------> feature/DBI-US003-22
Sufixo Props nas interface ---> export interface ComponetNameProps {}

2021-12-30 16:15 UTC, fabiojcbatista approved these changes

2021-12-30 17:23 UTC, eduardoaraya requested changes

2021-12-31 00:04 UTC, eduardoaraya approved these changes

2022-01-03 16:53 UTC, Luh-Santos approved these changes

2022-01-03 16:55 UTC, merged