Feature/dbi us001 12- US001 - [Front] - Menu de acessibilidade
dbinclui-org/dbinclui-frontend pull request #31
Opened 2021-12-30 17:05 UTC by ketrynsdm

## Descrição

Logica da acessibilidade (Fontes)

____

**Link do card:**
[US001 - [Front] - Menu de acessibilidade](https://trello.com/c/DezeILrz/12-us001-front-menu-de-acessibilidade)

____

## Checklist Code Review
Avaliar se todos os itens a seguir foram feitos. Os itens com `*` não são obrigatórios.

- [ ] Foi adicionada a descrição da PR
- [ ] Foi adicionado o link do card
- [ ] A branch segue o padrão com o prefixo DBI
- [ ] Está seguindo os padrões de prefixo do gitflow (feature, bugfix, hotfix, release)
- [ ] O título da PR segue o padrão: ***Nome da branch - Título do card***
- [ ] A PR está sendo enviada para a branch `develop`
- [ ] O Repositório que a PR está sendo enviada é o [**dbinclui-org/dbinclui-frontend**](https://github.com/dbinclui-org/dbinclui-frontend)
- [ ] Foi realizado os testes unitários *
- [ ] Foi realizado os testes de E2E *
- [ ] Foi adicionada as respectivas **labels**
- [ ] A PR foi assinada

Para que haja uma padronização na criação dos componentes, este deve seguir o seguinte modelo de construção:

- [ ] Deve ser feita a importação do _React_ no escopo do componente.
- [ ] Deve conter uma _interface_ com as propriedades do componente.
- [ ] Nome da _interface_ deve ter o sufixo _Props_.
- [ ] Recebe _React.FC_, no qual recebe a _interface_
- [ ] Deve retornar elemento _JSX_
- [ ] O componente de ser exportado ao final como `default`.
 
Exemplo:
```tsx
import React from 'react';

export interface ComponetNameProps {}

export const ComponetName: React.FC<ComponentNameProps> = (): JSX.Element => {
  return <>...</>;
};

export default ComponentName;
```

2021-12-30 17:27 UTC, eduardoaraya requested changes

2021-12-30 17:27 UTC, eduardoaraya commented on package.json
> +    "@types/jquery": "^3.5.11",
Remover jquery

2022-01-03 18:51 UTC, fabiojcbatista reviewed
Erro no debug. Precisa rodar npm run prettier:write

2022-01-04 19:46 UTC, fabiojcbatista reviewed
Erro no test -- > Checks

2022-01-04 20:27 UTC, eduardoaraya approved these changes

2022-01-04 20:52 UTC, Nicolasgbdas approved these changes

2022-01-04 20:55 UTC, fabiojcbatista approved these changes

2022-01-04 20:55 UTC, merged