Feature/US003/US007/US011-DBI-56 - Criação de um componente de mensagens de confirmação ou erro
dbinclui-org/dbinclui-frontend pull request #52
Opened 2022-01-07 20:54 UTC by arthurvergacas

## Descrição
Criar o componente de avisos para ser usado em toda a aplicação. Tornar esses avisos em componentes tanto facilita o uso no desenvolvimento quanto padroniza as mensagens.
____

**Link do card:**
[US003/US007/US011 - [Front] - Criação de um componente de mensagens de confirmação ou erro](https://trello.com/c/A5nJPWHU/56-3-us003-us007-us011-front-cria%C3%A7%C3%A3o-de-um-componente-de-mensagens-de-confirma%C3%A7%C3%A3o-ou-erro)

____

## Checklist Code Review
Avaliar se todos os itens a seguir foram feitos. Os itens com `*` não são obrigatórios.

- [ ] Foi adicionada a descrição da PR
- [ ] Foi adicionado o link do card
- [ ] A branch segue o padrão com o prefixo DBI
- [ ] Está seguindo os padrões de prefixo do gitflow (feature, bugfix, hotfix, release)
- [ ] O título da PR segue o padrão: ***Nome da branch - Título do card***
- [ ] A PR está sendo enviada para a branch `develop`
- [ ] O Repositório que a PR está sendo enviada é o [**dbinclui-org/dbinclui-frontend**](https://github.com/dbinclui-org/dbinclui-frontend)
- [ ] Foi realizado os testes unitários *
- [ ] Foi realizado os testes de E2E *
- [ ] Foi adicionada as respectivas **labels**
- [ ] A PR foi assinada

Para que haja uma padronização na criação dos componentes, este deve seguir o seguinte modelo de construção:

- [ ] Deve ser feita a importação do _React_ no escopo do componente.
- [ ] Deve conter uma _interface_ com as propriedades do componente.
- [ ] Nome da _interface_ deve ter o sufixo _Props_.
- [ ] Recebe _React.FC_, no qual recebe a _interface_
- [ ] Deve retornar elemento _JSX_
- [ ] O componente de ser exportado ao final como `default`.
 
Exemplo:
```tsx
import React from 'react';

export interface ComponetNameProps {}

export const ComponetName: React.FC<ComponentNameProps> = (): JSX.Element => {
  return <>...</>;
};

export default ComponentName;
```

2022-01-07 22:04 UTC, Antonia095 approved these changes

2022-01-07 22:05 UTC, fabiojcbatista approved these changes

2022-01-08 16:01 UTC, eduardoaraya requested changes

2022-01-08 16:01 UTC, eduardoaraya commented on src/components/Notification/notification.test.tsx
> +  });
Crie um teste para cada situação, quando o variant for de erro e sucesso

2022-01-10 12:20 UTC, eduardoaraya commented on src/components/Notification/index.tsx
> +        )}
Poderíamos definir uma função para essa validação e simplificar a leitura e abstrair mais a lógica.
A Validação serve para informar apenas o Título do componente.

```
const getTitleText = (title: string | null) => {
  if (!title) {
    return (variant === 'error') ? 'Erro' : 'Sucesso';
  }
  return title;
}

...

<AlertTitle title="Título da Notificação">{getTitleText(title)}</AlertTitle>
```

Essa propriedade title do componente é para o `HTML` ou seria alguma saída de texto em tela ?

2022-01-10 12:24 UTC, arthurvergacas commented on src/components/Notification/index.tsx
> +        )}
hummmmmmm boa boa
acho perfeito abstrair a função tbm
menos bagunça ali no meio do jsx ne ai pft pft

E essa propriedade `title` é tanto pra acessibilidade (pra que o leitor de tela saiba que aquilo é o título, da mesma forma que o MUI coloca um title escrito "fechar" no botão de fechar) quanto para os testes. 
 
Esse título aí não tinha nenhuma forma aparente (pelo menos a gnt n pensou em nenhuma ne akjsd) de ser queryado sem ser com title ou aquele `data-testid`. E como a documentação recomenda usar o `testid` só em último caso a gnt resolveu usar o title. Vc acha q tem problema??

2022-01-10 12:32 UTC, eduardoaraya commented on src/components/Notification/index.tsx
> +        )}
Não vejo problema, acho que poderia concatenar com o título original por exemplo: `Título da Notificação: Sucesso`

2022-01-10 12:32 UTC, arthurvergacas commented on src/components/Notification/index.tsx
> +        )}
hummmmmmmmmmmmmmmmmmmmmmmmmmm boa ideia boa ideia
ok vou fazer isso ent

2022-01-10 13:42 UTC, eduardoaraya requested changes

2022-01-10 13:42 UTC, eduardoaraya commented on src/components/Notification/index.tsx
> +          {getNotificationTitle(title)}
Associe o título da notificação a uma variável e chame ela quando necessário. A função `getNotificationTitile()` está sendo chamada 2x. 

```
const notificationTitle = getNotificationTitle(title);

return ( ...
    <AlertTitle title={`Título da Notificação: ${notificationTitle}`}>
        {notificationTitle}
    </AlertTitle>
...);
```

2022-01-10 13:42 UTC, eduardoaraya commented on src/components/Notification/notification.test.tsx
> +import Notification from '.';
Utilize os paths que definimos no projeto.
```
import Notification from '@components/Notification'

2022-01-10 13:57 UTC, eduardoaraya approved these changes

2022-01-10 13:57 UTC, merged