Feature/DBI-US003-58 - US003 - Front - Implementar a funcionalidade botão Salvar
dbinclui-org/dbinclui-frontend pull request #55
Opened 2022-01-11 14:30 UTC by nickolasL13

## Descrição

Foi feita a implementação do botão salvar ajustado com mensagens de confirmação e erro, e foi realizado os testesunitários.

____

**Link do card:**
[(4) US003 - Front - Implementar a funcionalidade botão Salvar](https://trello.com/c/7b2h45GO/58-4-us003-front-implementar-a-funcionalidade-bot%C3%A3o-salvar)

____

## Checklist Code Review
Avaliar se todos os itens a seguir foram feitos. Os itens com `*` não são obrigatórios.

- [x] Foi adicionada a descrição da PR
- [x] Foi adicionado o link do card
- [x] A branch segue o padrão com o prefixo DBI
- [x] Está seguindo os padrões de prefixo do gitflow (feature, bugfix, hotfix, release)
- [x] O título da PR segue o padrão: ***Nome da branch - Título do card***
- [x] A PR está sendo enviada para a branch `develop`
- [x] O Repositório que a PR está sendo enviada é o [**dbinclui-org/dbinclui-frontend**](https://github.com/dbinclui-org/dbinclui-frontend)
- [ ] Foi realizado os testes unitários *
- [ ] Foi realizado os testes de E2E *
- [x] Foi adicionada as respectivas **labels**
- [x] A PR foi assinada

Para que haja uma padronização na criação dos componentes, este deve seguir o seguinte modelo de construção:

- [ ] Deve ser feita a importação do _React_ no escopo do componente.
- [ ] Deve conter uma _interface_ com as propriedades do componente.
- [ ] Nome da _interface_ deve ter o sufixo _Props_.
- [ ] Recebe _React.FC_, no qual recebe a _interface_
- [ ] Deve retornar elemento _JSX_
- [ ] O componente de ser exportado ao final como `default`.
 
Exemplo:
```tsx
import React from 'react';

export interface ComponetNameProps {}

export const ComponetName: React.FC<ComponentNameProps> = (): JSX.Element => {
  return <>...</>;
};

export default ComponentName;
```

2022-01-11 14:31 UTC, nickolasL13 commented
Esperar PR de atualização do botão de Confirmação e Erro para executar merge

2022-01-11 15:14 UTC, nickolasL13 commented on src/pages/register-guide/index.tsx
> +      {success && <Notification message='Cadastro ralizado com sucesso! ✔' variant='success'/>}
👍

2022-01-11 16:21 UTC, Luh-Santos approved these changes

2022-01-11 16:29 UTC, fabiojcbatista reviewed
Atualização de path

2022-01-11 16:29 UTC, fabiojcbatista commented on src/pages/acessibility-guide/index.tsx
>  import AccessibilityTypography from '../../components/AccessibilityTypography';
Precisa atualizar os path

2022-01-11 16:51 UTC, eduardoaraya commented on src/pages/acessibility-guide/index.tsx
>  import AccessibilityTypography from '../../components/AccessibilityTypography';
utilizar os paths:

```
import  { CardGuidesResponse, getGuides } from @services/Guides/guides;

2022-01-11 16:58 UTC, eduardoaraya requested changes
Acho que podemos utilizar o padrão de manter o nome das pastas em minúscula e ao inves de ter um arquivo chamado guides.ts, trocar para index.ts. 

Vamos adicionar os testes do guides service ali tbm, n necessitando mais daquela pasta `tests`.

2022-01-11 19:02 UTC, nickolasL13 commented on src/pages/acessibility-guide/index.tsx
>  import AccessibilityTypography from '../../components/AccessibilityTypography';
Feito

2022-01-12 14:27 UTC, arthurvergacas commented on src/pages/register-guide/RegisterGuide.test.tsx
> +    screen.debug()
Tem um `screen.debug()` que eu suponho que não era pra estar aqui, n sei

2022-01-12 14:27 UTC, arthurvergacas commented on src/pages/register-guide/RegisterGuide.test.tsx
> +// await new Promise((r) => setTimeout(r, 2000));
e aqui um comentário aleatório

2022-01-12 16:18 UTC, fabiojcbatista reviewed
Comment

2022-01-12 16:18 UTC, fabiojcbatista commented on src/services/Guides/index.ts
> +import api from '../api';
Atualizar o path

2022-01-12 16:19 UTC, fabiojcbatista reviewed
Comment

2022-01-12 16:19 UTC, fabiojcbatista commented on src/pages/register-guide/index.tsx
>  import validateInput from './validator';
atualizar o path

2022-01-12 21:22 UTC, arthurvergacas commented on src/pages/acessibility-guide/index.tsx
> +import CardGuidesResponse, { getGuides } from '@services/Guides';
acho que aqui precisa deixar `Guides` no minúsculo mesmo. mas n sei tbm essa pasta já mudou de nome tantas vezes nem sei mais

2022-01-12 22:27 UTC, pliniogoncalves approved these changes

2022-01-12 22:39 UTC, arthurvergacas approved these changes

2022-01-12 22:49 UTC, nickolasL13 commented on src/pages/acessibility-guide/index.tsx
> +import CardGuidesResponse, { getGuides } from '@services/Guides';
É minusculo mesmo. Thanks

2022-01-12 22:57 UTC, nickolasL13 commented on src/pages/acessibility-guide/index.tsx
> +import CardGuidesResponse, { getGuides } from '@services/Guides';
Muito sus isso aí, pq no meu tá guides minúsculo 🤔

2022-01-13 12:45 UTC, fabiojcbatista requested changes

2022-01-13 12:45 UTC, fabiojcbatista commented on src/services/guides/index.ts
> +    return api.post('/register', cardBody);
As rotas estão sendo atualizadas através do [card](https://trello.com/c/29tTI7bY/41-1-us007-back-criar-rota-para-p%C3%A1gina) para:

1 - buscar as guias: /guides/list
2 - incluir guia: /guides/register

Verificar com @LizSantana e @Nicolasgbdas

2022-01-13 12:47 UTC, LizSantana commented on src/services/guides/index.ts
> +    return api.post('/register', cardBody);
É exatamente isso mesmo.

2022-01-13 14:37 UTC, eduardoaraya approved these changes

2022-01-13 14:50 UTC, fabiojcbatista approved these changes

2022-01-13 14:50 UTC, merged