Feature/DBI-US001-18-S2- Acessibilidade -  contraste e aumentar ou diminuir a fonte
dbinclui-org/dbinclui-frontend pull request #69
Opened 2022-01-17 22:08 UTC by DayMendes

## Descrição

Implementação do botão contraste, ajuste do layout para aumento e recuo da fonte, alteração da logo, mudança de contraste na logo e na página erro 404, adicionando novas variaveis no tema global.

____

**Link do card:**
[[feature/DBI-US001-18-S2 - Acessibilidade -  contraste e aumentar ou diminuir a fonte](https://trello.com/c/5hDDcriJ/18-10-d%C3%A9bito-t%C3%A9cnico-acessibilidade-contraste-e-aumentar-ou-diminuir-a-fonte)]

____

## Checklist Code Review
Avaliar se todos os itens a seguir foram feitos. Os itens com `*` não são obrigatórios.

- [ ] Foi adicionada a descrição da PR
- [ ] Foi adicionado o link do card
- [ ] A branch segue o padrão com o prefixo DBI
- [ ] Está seguindo os padrões de prefixo do gitflow (feature, bugfix, hotfix, release)
- [ ] O título da PR segue o padrão: ***Nome da branch - Título do card***
- [ ] A PR está sendo enviada para a branch `develop`
- [ ] O Repositório que a PR está sendo enviada é o [**dbinclui-org/dbinclui-frontend**](https://github.com/dbinclui-org/dbinclui-frontend)
- [ ] Foi realizado os testes unitários *
- [ ] Foi realizado os testes de E2E *
- [ ] Foi adicionada as respectivas **labels**
- [ ] A PR foi assinada

Para que haja uma padronização na criação dos componentes, este deve seguir o seguinte modelo de construção:

- [ ] Deve ser feita a importação do _React_ no escopo do componente.
- [ ] Deve conter uma _interface_ com as propriedades do componente.
- [ ] Nome da _interface_ deve ter o sufixo _Props_.
- [ ] Recebe _React.FC_, no qual recebe a _interface_
- [ ] Deve retornar elemento _JSX_
- [ ] O componente de ser exportado ao final como `default`.
 
Exemplo:
```tsx
import React from 'react';

export interface ComponetNameProps {}

export const ComponetName: React.FC<ComponentNameProps> = (): JSX.Element => {
  return <>...</>;
};

export default ComponentName;
```

2022-01-17 22:10 UTC, fabiojcbatista reviewed
Comment

2022-01-17 22:10 UTC, fabiojcbatista commented on src/App.tsx
>  import Routers from './routes/routes';
Atualizar o path

2022-01-17 22:13 UTC, fabiojcbatista reviewed
Comment

2022-01-17 22:13 UTC, fabiojcbatista commented on src/components/Header/index.tsx
> +import AccessibilityTypography from '../../components/AccessibilityTypography';
Atualizar o path

2022-01-17 22:15 UTC, fabiojcbatista reviewed
Comment

2022-01-17 22:15 UTC, fabiojcbatista commented on src/pages/error/404.tsx
> +import * as React from 'react';
Atualizar path

2022-01-17 22:34 UTC, fabiojcbatista requested changes
Correção nos testes

2022-01-18 15:52 UTC, arthurvergacas commented on src/components/Header/styles.css
> +  /* margin: 1rem; */
Comentário perdido

2022-01-18 15:52 UTC, arthurvergacas commented on src/components/AcessibilityTools/AccessibilityTools.test.tsx
> +    const { getByLabelText, getByText } = render(
Por que ta usando os metodos do render ao invés de usar `screen.getByText`?? Se usa o `screen` não precisa dos comentário do eslint e fica mais coerente

2022-01-18 15:52 UTC, arthurvergacas commented on src/pages/error/404.tsx
> +            </Typography>
Prestar atenção aqui pois a gente corre o risco de ter um dom do tipo:

```html
<p>
  <p>
    ...
  </p>
</p>
```

E isso causa um warning de elementos de parágrafo aninhados. Vejam se não é melhor usar só um typography ao invés de dois aninhados. nesse caso parece ser possível, mas não tenho ctz, teria que testar

2022-01-18 15:52 UTC, arthurvergacas commented on src/pages/register-guide/index.tsx
> +            <AccessibilityTypography sx={styles.headerTitle}>
aqui tirou o `variant="h1"`. Isso quer dizer que não é um h1 mais?? mas isso não prejudica a semântica do documento? afinal o padrão é um `p` ne, e aqui pelo oq eu entendi ele está agindo com título. nas outras páginas de registro pelo oq eu vi aconteceu a mesma coisa, então tem que ver isso

2022-01-18 15:54 UTC, arthurvergacas commented on src/components/Header/header.test.tsx
> +    const { getByTitle } = render(
isso aqui acontece em outros testes tbmm, só n marquei pra n ter mt coisa

2022-01-18 17:19 UTC, fabiojcbatista approved these changes
Teste ok

2022-01-18 21:46 UTC, fabiojcbatista approved these changes

2022-01-19 13:09 UTC, arthurvergacas approved these changes

2022-01-19 13:10 UTC, Luh-Santos approved these changes

2022-01-19 13:10 UTC, merged